version = 0.1
default-task = 'build'

extensions = ['chomp@0.1:swc']

[[task]]
name = 'build'
deps = ['app.html']

[[task]]
target = 'lib/#.js'
dep = 'src/#.ts'
template = 'swc'
[task.template-options]
'jsc.target' = 'es2019'
source-maps = false

[[task]]
target = 'app.html'
deps = ['app.html', 'lib/**/*.js']
engine = 'node'
run = '''
import { Generator } from '@jspm/generator';
import { readFile, writeFile } from 'fs/promises';
import { pathToFileURL } from 'url';

const generator = new Generator({
  mapUrl: pathToFileURL('app.html'),
  env: ['production', 'browser', 'module']
});

const htmlSource = await readFile('app.html', 'utf-8');

await writeFile('app.html', await generator.htmlGenerate(htmlSource, {
  preload: true,
  integrity: true
}));
'''
